package com.trungnguyen.springmail.domain;

import java.time.LocalDate;
import java.util.Date;

public class RpKpiCbclDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private LocalDate day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String center;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String subTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingA1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeA1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingA2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeA2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingA3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeA3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingCore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeCore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingRan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeRan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingTd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeTd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingKhvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntimeKhvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingRanTrain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Integer handlingOnRanTrain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public LocalDate getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @param day the value for SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setDay(LocalDate day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @param center the value for SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setCenter(String center) {
        this.center = center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @param team the value for SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setTeam(String team) {
        this.team = team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getSubTeam() {
        return subTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @param subTeam the value for SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setSubTeam(String subTeam) {
        this.subTeam = subTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @param username the value for SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingA1() {
        return handlingA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @param handlingA1 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingA1(Integer handlingA1) {
        this.handlingA1 = handlingA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeA1() {
        return handlingOntimeA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @param handlingOntimeA1 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeA1(Integer handlingOntimeA1) {
        this.handlingOntimeA1 = handlingOntimeA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingA2() {
        return handlingA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @param handlingA2 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingA2(Integer handlingA2) {
        this.handlingA2 = handlingA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeA2() {
        return handlingOntimeA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @param handlingOntimeA2 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeA2(Integer handlingOntimeA2) {
        this.handlingOntimeA2 = handlingOntimeA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingA3() {
        return handlingA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @param handlingA3 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingA3(Integer handlingA3) {
        this.handlingA3 = handlingA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeA3() {
        return handlingOntimeA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @param handlingOntimeA3 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeA3(Integer handlingOntimeA3) {
        this.handlingOntimeA3 = handlingOntimeA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingCore() {
        return handlingCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @param handlingCore the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingCore(Integer handlingCore) {
        this.handlingCore = handlingCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeCore() {
        return handlingOntimeCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @param handlingOntimeCore the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeCore(Integer handlingOntimeCore) {
        this.handlingOntimeCore = handlingOntimeCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingRan() {
        return handlingRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @param handlingRan the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingRan(Integer handlingRan) {
        this.handlingRan = handlingRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeRan() {
        return handlingOntimeRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @param handlingOntimeRan the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeRan(Integer handlingOntimeRan) {
        this.handlingOntimeRan = handlingOntimeRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingTd() {
        return handlingTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @param handlingTd the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingTd(Integer handlingTd) {
        this.handlingTd = handlingTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeTd() {
        return handlingOntimeTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @param handlingOntimeTd the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeTd(Integer handlingOntimeTd) {
        this.handlingOntimeTd = handlingOntimeTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingKhvip() {
        return handlingKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @param handlingKhvip the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingKhvip(Integer handlingKhvip) {
        this.handlingKhvip = handlingKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntimeKhvip() {
        return handlingOntimeKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @param handlingOntimeKhvip the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeKhvip(Integer handlingOntimeKhvip) {
        this.handlingOntimeKhvip = handlingOntimeKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandling() {
        return handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @param handling the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandling(Integer handling) {
        this.handling = handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOntime() {
        return handlingOntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @param handlingOntime the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntime(Integer handlingOntime) {
        this.handlingOntime = handlingOntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingRanTrain() {
        return handlingRanTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @param handlingRanTrain the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingRanTrain(Integer handlingRanTrain) {
        this.handlingRanTrain = handlingRanTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Integer getHandlingOnRanTrain() {
        return handlingOnRanTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @param handlingOnRanTrain the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOnRanTrain(Integer handlingOnRanTrain) {
        this.handlingOnRanTrain = handlingOnRanTrain;
    }
}