package com.trungnguyen.springmail.domain;

import java.util.Date;

public class RpKpiCbclDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Date day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String center;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String subTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingA1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeA1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingA2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeA2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingA3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeA3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingCore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeCore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingRan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeRan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingTd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeTd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingKhvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntimeKhvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingRanTrain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    private Short handlingOnRanTrain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @param day the value for SMARTW.RP_KPI_CBCL_DAILY.DAY
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @param center the value for SMARTW.RP_KPI_CBCL_DAILY.CENTER
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setCenter(String center) {
        this.center = center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @param team the value for SMARTW.RP_KPI_CBCL_DAILY.TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setTeam(String team) {
        this.team = team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getSubTeam() {
        return subTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @param subTeam the value for SMARTW.RP_KPI_CBCL_DAILY.SUB_TEAM
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setSubTeam(String subTeam) {
        this.subTeam = subTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @param username the value for SMARTW.RP_KPI_CBCL_DAILY.USERNAME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingA1() {
        return handlingA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @param handlingA1 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingA1(Short handlingA1) {
        this.handlingA1 = handlingA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeA1() {
        return handlingOntimeA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @param handlingOntimeA1 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A1
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeA1(Short handlingOntimeA1) {
        this.handlingOntimeA1 = handlingOntimeA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingA2() {
        return handlingA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @param handlingA2 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingA2(Short handlingA2) {
        this.handlingA2 = handlingA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeA2() {
        return handlingOntimeA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @param handlingOntimeA2 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A2
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeA2(Short handlingOntimeA2) {
        this.handlingOntimeA2 = handlingOntimeA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingA3() {
        return handlingA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @param handlingA3 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingA3(Short handlingA3) {
        this.handlingA3 = handlingA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeA3() {
        return handlingOntimeA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @param handlingOntimeA3 the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_A3
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeA3(Short handlingOntimeA3) {
        this.handlingOntimeA3 = handlingOntimeA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingCore() {
        return handlingCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @param handlingCore the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingCore(Short handlingCore) {
        this.handlingCore = handlingCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeCore() {
        return handlingOntimeCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @param handlingOntimeCore the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_CORE
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeCore(Short handlingOntimeCore) {
        this.handlingOntimeCore = handlingOntimeCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingRan() {
        return handlingRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @param handlingRan the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingRan(Short handlingRan) {
        this.handlingRan = handlingRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeRan() {
        return handlingOntimeRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @param handlingOntimeRan the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_RAN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeRan(Short handlingOntimeRan) {
        this.handlingOntimeRan = handlingOntimeRan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingTd() {
        return handlingTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @param handlingTd the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingTd(Short handlingTd) {
        this.handlingTd = handlingTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeTd() {
        return handlingOntimeTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @param handlingOntimeTd the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_TD
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeTd(Short handlingOntimeTd) {
        this.handlingOntimeTd = handlingOntimeTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingKhvip() {
        return handlingKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @param handlingKhvip the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingKhvip(Short handlingKhvip) {
        this.handlingKhvip = handlingKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntimeKhvip() {
        return handlingOntimeKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @param handlingOntimeKhvip the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME_KHVIP
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntimeKhvip(Short handlingOntimeKhvip) {
        this.handlingOntimeKhvip = handlingOntimeKhvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandling() {
        return handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @param handling the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandling(Short handling) {
        this.handling = handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOntime() {
        return handlingOntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @param handlingOntime the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ONTIME
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOntime(Short handlingOntime) {
        this.handlingOntime = handlingOntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingRanTrain() {
        return handlingRanTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @param handlingRanTrain the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingRanTrain(Short handlingRanTrain) {
        this.handlingRanTrain = handlingRanTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @return the value of SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public Short getHandlingOnRanTrain() {
        return handlingOnRanTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @param handlingOnRanTrain the value for SMARTW.RP_KPI_CBCL_DAILY.HANDLING_ON_RAN_TRAIN
     *
     * @mbg.generated Sat Apr 30 18:07:22 ICT 2022
     */
    public void setHandlingOnRanTrain(Short handlingOnRanTrain) {
        this.handlingOnRanTrain = handlingOnRanTrain;
    }
}